### ISSUE TITLE
Incorrect behavior when memcached server dies / loses connection

### ISSUE THREAD

**Issue by iniva** [hapijs/catbox-memcached#27] opened 2018-05-01 21:05 UTC
[Mentioned](https://github.com/hapijs/catbox-memcached/pull/26#issuecomment-384445945) by @jamesgibson14 in #26

If memcached server dies the request doesn't timeout.

**Comment by iniva** [comment] 2018-05-01 21:10
I've been trying to understand why this happens. Until now I've managed to make it throw an error that triggers the driver's `stop()` method.

Still, it seems as if `catbox` is shadowing the error, avoiding `catbox-memcached` to handle it. This is just a thought.

Help is welcomed.

**Comment by hueniverse** [comment] 2018-11-11 01:54
Since this cannot be reproduced, I suggest we close this and wait for fresh reports.

**Closed by hueniverse** 2018-11-11 01:54 UTC
Labels: bug
